import {useEffect,useState} from "react";
import ReactMarkdown from "react-markdown";
import {RefreshCw,Sparkles} from "lucide-react";
import AsciiBox from "./AsciiBox";
import GradientText from "./GradientText";
import LuckyTime from "./LuckyTime";
import StarMap from "./StarMap";
import {getPersonalDayNumber,getDayRuler,getDayColors,getDayCrystals,NUMEROLOGY_MEANINGS,COLOR_MEANINGS,CRYSTAL_MEANINGS,PLANETS,todayKey,formatDate} from "../../lib/astrology";
import {generateReading} from "../../lib/llm";
import {getRaw,setRaw} from "../../lib/storage";
export default function DailyReport({profile}){
 const now=new Date(),key=`astralis_daily_${todayKey(now)}`,pd=getPersonalDayNumber(profile.birth_date,now),ruler=getDayRuler(now),colors=getDayColors(now),crystals=getDayCrystals(now),num=NUMEROLOGY_MEANINGS[pd];
 const [report,setReport]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const fetchReport=async(force=false)=>{setError("");if(!force){const cached=getRaw(key,"");if(cached){setReport(cached);return;}}if(!getRaw("astralis_gemini_key","")){setError("NO_KEY");return;}setLoading(true);try{const text=await generateReading({kind:"daily",payload:{birth_date:profile.birth_date,birth_time:profile.birth_time,birth_location:profile.birth_location,sun_sign:profile.sun_sign,life_path_number:profile.life_path_number,personal_day_number:pd,day_ruler:ruler,date_string:formatDate(now)}});setReport(text);setRaw(key,text);}catch(e){setError(e.code==="NO_GEMINI_KEY"?"NO_KEY":e.message)}finally{setLoading(false)}};
 useEffect(()=>{fetchReport(false)},[key]);
 const markdown={h2:({children})=><GradientText as="h2" className="font-heading text-xl block">{children}</GradientText>,p:({children})=><p className="leading-relaxed mb-3 text-[1.05rem]">{children}</p>,li:({children})=><li className="leading-relaxed ml-4 list-disc">{children}</li>,strong:({children})=><strong className="uv-text">{children}</strong>};
 return <section className="mt-8"><AsciiBox title="Today's Correspondences" glyph="✧"><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{[["Personal Day",pd,num.title],["Ruled By",`${PLANETS[ruler].symbol} ${ruler}`,PLANETS[ruler].domain.split(".")[0]+"."],["Color Magic",colors[0],COLOR_MEANINGS[colors[0]]],["Crystal",crystals[0],CRYSTAL_MEANINGS[crystals[0]]]].map(([a,b,c])=><div className="uv-border-soft p-3" key={a}><p className="font-mono text-[9px] uppercase tracking-wider">{a}</p><GradientText as="p" className="font-heading text-lg block mt-1">{b}</GradientText><p className="text-xs mt-1 opacity-80">{c}</p></div>)}</div><div className="border-t border-dashed border-fuchsia/20 my-5"/><div className="grid sm:grid-cols-3 gap-4 text-sm"><div><p className="font-mono text-[9px]">NUMEROLOGY · {pd}</p><p className="mt-1">{num.meaning}</p></div><div><p className="font-mono text-[9px]">WEAR / SURROUND WITH</p><p className="mt-1">{colors.join(" · ")}</p></div><div><p className="font-mono text-[9px]">CARRY THESE STONES</p><p className="mt-1">{crystals.join(" · ")}</p></div></div></AsciiBox><LuckyTime/><AsciiBox title="The Cosmic Insight" glyph="✦" className="mt-7"><div className="flex justify-between items-center mb-5"><div className="flex gap-2 items-center"><Sparkles size={17}/><GradientText as="span" className="font-mono text-[10px]">{formatDate(now)}</GradientText></div><button onClick={()=>fetchReport(true)} disabled={loading} title="Refresh reading"><RefreshCw size={16} className={loading?"animate-spin":""}/></button></div>{loading?<div className="text-center py-8"><StarMap variant="lyre" className="w-64 max-w-full mx-auto animate-twinkle"/><p className="font-mono text-xs mt-3">Consulting today's ephemeris…</p></div>:error==="NO_KEY"?<div className="text-center py-7"><p className="font-heading text-lg">Your local sky tools are ready.</p><p className="text-sm mt-2">Add your Gemini API key using the ⚙ Settings control to unlock today's deep, grounded reading.</p></div>:error?<div className="text-center py-7"><p className="text-red-300/80 font-mono text-xs">The reading could not be completed.</p><p className="text-sm mt-2 opacity-75">{error}</p><button onClick={()=>fetchReport(true)} className="mt-4 px-4 py-2 border border-fuchsia/40 bg-fuchsia/10"><span>Try again</span></button></div>:report?<div className="prose-astro">{<ReactMarkdown components={markdown}>{report}</ReactMarkdown>}</div>:null}</AsciiBox></section>;
}