import {useEffect,useState} from "react";
import ReactMarkdown from "react-markdown";
import {RefreshCw} from "lucide-react";
import AsciiBox from "./AsciiBox";
import GradientText from "./GradientText";
import ZodiacWheel from "./ZodiacWheel";
import {getSunSign} from "../../lib/astrology";
import {generateReading} from "../../lib/llm";
import {getRaw,setRaw,removeStored} from "../../lib/storage";
export default function NatalChartCard({profile}){
 const key="astralis_natal_chart",sun=getSunSign(profile.birth_date),[report,setReport]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const fetchReport=async(force=false)=>{setError("");if(!force){const cached=getRaw(key,"");if(cached){setReport(cached);return;}}if(!getRaw("astralis_gemini_key","")){setError("NO_KEY");return;}setLoading(true);try{const text=await generateReading({kind:"natal",payload:{birth_date:profile.birth_date,birth_time:profile.birth_time,birth_location:profile.birth_location,name:profile.name}});setReport(text);setRaw(key,text)}catch(e){setError(e.code==="NO_GEMINI_KEY"?"NO_KEY":e.message)}finally{setLoading(false)}};
 useEffect(()=>{fetchReport(false)},[profile.birth_date]);
 const md={h1:({children})=><GradientText as="h2" className="font-heading text-2xl block">{children}</GradientText>,h2:({children})=><GradientText as="h3" className="font-heading text-xl block">{children}</GradientText>,h3:({children})=><GradientText as="h4" className="font-heading text-lg block">{children}</GradientText>,p:({children})=><p className="leading-relaxed mb-3 text-[1.05rem]">{children}</p>,li:({children})=><li className="leading-relaxed ml-4 list-disc">{children}</li>};
 return <div className="animate-fade-up"><div className="mb-7"><GradientText as="h1" className="font-heading text-3xl sm:text-4xl block">YOUR NATAL CHART</GradientText><p className="font-mono text-[9px] uppercase tracking-wider mt-2">{profile.name} · {profile.birth_date}{profile.birth_time?` at ${profile.birth_time}`:""} · {profile.birth_location}</p></div><div className="grid md:grid-cols-[260px_1fr] gap-5"><AsciiBox title="The Wheel" glyph="◈" bodyClassName="text-center"><ZodiacWheel highlight={sun?.name} size={220} className="mx-auto animate-float-slow"/><GradientText as="p" className="font-heading text-xl block mt-4">{sun?.symbol} {sun?.name}</GradientText><p className="text-xs mt-1">{sun?.element} · {sun?.modality}</p><p className="text-xs italic mt-2">{sun?.keywords}</p></AsciiBox><AsciiBox title="The Reading" glyph="✦"><div className="flex justify-end mb-2"><button onClick={()=>{removeStored(key);fetchReport(true)}} disabled={loading} title="Refresh reading"><RefreshCw size={16} className={loading?"animate-spin":""}/></button></div>{loading?<div className="text-center py-10"><p className="font-mono text-xs">Casting and verifying the natal sky…</p></div>:error==="NO_KEY"?<div className="text-center py-10"><p className="font-heading text-lg">Your wheel is ready.</p><p className="text-sm mt-2">Add your Gemini API key in Settings to unlock the deep natal interpretation.</p></div>:error?<div className="text-center py-10"><p className="text-sm">The reading failed.</p><p className="text-xs mt-2 opacity-70">{error}</p><button onClick={()=>fetchReport(true)} className="mt-4 px-4 py-2 border border-fuchsia/40"><span>Try again</span></button></div>:report?<div className="prose-astro"><ReactMarkdown components={md}>{report}</ReactMarkdown></div>:null}</AsciiBox></div></div>;
}